### ISSUE TITLE
Attempting to authenticate causes a json error

### ISSUE THREAD

**Issue by 499602D2** [tomquirk/linkedin-api#100]
`DEBUG:linkedin_api.client:Attempting to use cached cookies`

`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.linkedin.com:443`

`DEBUG:urllib3.connectionpool:https://www.linkedin.com:443 "POST /uas/authenticate HTTP/1.1" 400 0`

`Expecting value: line 1 column 1 (char 0)`

Not sure how to go about solving this, or what is causing it in the first place: could be a json error. Same error appears when authenticating and refreshing cookies.

**Comment by 499602D2** [comment]
```
29/06/2020 17:54:15 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "my_file.py", line 156, in authenticate
    self.application = Linkedin(self.username, self.password, debug=True, refresh_cookies=refresh_cookies)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/linkedin_api/linkedin.py", line 52, in __init__
    self.client.authenticate(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/linkedin_api/client.py", line 95, in authenticate
    return self._do_authentication_request(username, password)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/linkedin_api/client.py", line 119, in _do_authentication_request
    data = res.json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tomquirk** [comment]
@499602D2 Thanks for submitting this. I've tested locally with and without cached cookies and it's all working for me.

I am running Python 3.7 however, which I doubt would make a difference, but could be worth checking.

If the `POST /uas/authenticate` is giving a `400` though, I would double check that your `self.username` and `self.password` definitely exist.

**Comment by 499602D2** [comment]
I'm running 3.8.3, and the issue occurs on both machines I have. What's odd is that sometimes I get the valid `200` response, and sometimes I don't. Most of the time I manage to log in on the first try, but if I close the program and attempt to re-login, I can't get back in, even when trying with either cookie setting. Only fix that works in that case is to wait for a while — it's almost as if LinkedIn is choosing to ignore my login requests.

**Comment by 499602D2** [comment]
Okay, so this was an issue on my end: the authentication failed due to, as @tomquirk expected, due to invalid `self.username` and `self.password`. What made it weird was that it only failed _most of the time_ when loading them from a config file, thanks to some other interactions. The login worked always when taking them as direct input, which I rarely used, due to the complexity of the passwords used.
