### ISSUE TITLE
Error when I use search function

### ISSUE THREAD

**Issue by mmizab** [tomquirk/linkedin-api#13]
Search function isnt working
*search term*: `'starshot software'`

```Traceback (most recent call last):
  File "basic.py", line 6, in <module>
    linkedin.search('starshot software');
  File "/usr/local/lib/python3.6/site-packages/linkedin_api/linkedin.py", line 42, in search
    default_params.update(params)
ValueError: dictionary update sequence element #0 has length 1; 2 is required```

**Comment by tomquirk** [comment]
Hey @mmizab ,

To use `search`, your argument needs to be a `dict`. See [the docs](https://github.com/tomquirk/linkedin-api/blob/master/DOCS.md#search) for details.

You should try the following:
```python
results = linkedin.search({ 'keywords': 'starshot software' })
```
