### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by hybla0** [tomquirk/linkedin-api#141]
hello,
i used the provided example in the 'examples' folder but i get the below error
I logged in manually to linkedin and i completed i captcha challenge but i still got the same result.

Traceback (most recent call last):
  File "basic.py", line 6, in <module>
    linkedin = Linkedin(user, pwd)
  File "/home/lubuntu/.local/lib/python3.6/site-packages/linkedin_api/linkedin.py", line 69, in __init__
    self.client.authenticate(username, password)
  File "/home/lubuntu/.local/lib/python3.6/site-packages/linkedin_api/client.py", line 99, in authenticate
    self._fetch_metadata()
  File "/home/lubuntu/.local/lib/python3.6/site-packages/linkedin_api/client.py", line 121, in _fetch_metadata
    "meta", attrs={"name": "applicationInstance"}
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by pinnamaneni2005** [comment]
Hi hybla0,

Even I am facing this issue. Any workaround for this?

Traceback (most recent call last):
  File "Linkdn_API_demo.py", line 60, in <module>
    CreateConfig()
  File "Linkdn_API_demo.py", line 32, in CreateConfig
    api = Linkedin(username, password)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/linkedin_api/linkedin.py", line 69, in __init__
    self.client.authenticate(username, password)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/linkedin_api/client.py", line 99, in authenticate
    self._fetch_metadata()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/linkedin_api/client.py", line 120, in _fetch_metadata
    clientApplicationInstanceRaw = soup.find(
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by marcelogrsp** [comment]
I got the same problem today and sorted it!
Go to `LinkedinApiSettings.COOKIE_PATH` on windows: 
```
C:\Users\<username>\.linkedin_api\cookies
```
 and delete the cookies.jr file and run it again.

**Comment by pinnamaneni2005** [comment]
Thanks a lot, Marcelo.

**Comment by ChintalaRaju** [comment]
Hi Marcelo,

After clearing the jr file, for each request, it is navigating to the security page. Previously, we didn't have any issues by using this script but now we are unable to extract the data.

**Comment by PMLS3** [comment]
> I got the same problem today and sorted it!
> Go to `LinkedinApiSettings.COOKIE_PATH` on your linux:
> 
> ```
> /home/ubuntu/.linkedin_api/cookies/
> ```
> 
> on windows:
> 
> ```
> C:\Users\<username>\.linkedin_api\cookies
> ```
> 
> and delete the cookies.jr file and run it again.

Thanks, this worked for me, window Users/{user_name}/.linkedin_api/cookies
