### ISSUE TITLE
JSON decode error, no data on getting profile

### ISSUE THREAD

**Issue by himat** [tomquirk/linkedin-api#272]
The package worked for me a few weeks ago but is now no longer working for some reason.

Here's my simple code:
```
from linkedin_api import Linkedin

api: Unknown  = Linkedin('***', '***')

# GET a profile
profile: Unknown  = api.get_profile('billy-g')
print(profile)
```

When using the `https://github.com/tomquirk/linkedin-api.git` version of the package, this fails with 

```
Traceback (most recent call last):
  File "/Users/hima/Workspace/del/.venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/hima/.pyenv/versions/3.10.4/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/hima/.pyenv/versions/3.10.4/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/hima/.pyenv/versions/3.10.4/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hima/Workspace/del/run.py", line 6, in <module>
    profile = api.get_profile('billy-g')
  File "/Users/hima/Workspace/del/.venv/lib/python3.10/site-packages/linkedin_api/linkedin.py", line 622, in get_prof
ile
    data = res.json()
  File "/Users/hima/Workspace/del/.venv/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

---

When using the 2.0.0a version of the package,
it fails during authentication instead with
```
Traceback (most recent call last):
  File "/Users/hima/Workspace/del/run.py", line 3, in <module>
    api = Linkedin('***', '***')
  File "/Users/hima/Workspace/del/.venv/lib/python3.10/site-packages/linkedin_api/linkedin.py", line 69, in __init__
    self.client.authenticate(username, password)
  File "/Users/hima/Workspace/del/.venv/lib/python3.10/site-packages/linkedin_api/client.py", line 99, in authenticat
e
    self._fetch_metadata()
  File "/Users/hima/Workspace/del/.venv/lib/python3.10/site-packages/linkedin_api/client.py", line 122, in _fetch_met
adata
    ).attrs["content"]
AttributeError: 'NoneType' object has no attribute 'attrs'
```

I'm on python `3.10.4`

Any ideas why?

**Comment by himat** [comment]
I got the same error on 3.7.16 too

**Comment by Merlin1A** [comment]
Alright so after struggling with this same issue, I have figured out the root cause in my case. My error output is essentially the same as yours, but with a slight difference in the second line in the error output. Also note, I am using `Python version 3.10.4`.

The error has to do with the saved cookie/ cookies. In order to get a quick fix for the error, simply go to the place where the linkedin-api code places your cookies and delete all cookies in that folder.

In order to find that folder, I simply looked in the `settings.py` file and found the `COOKIE_PATH` variable. That variable corresponds to your home directory, which should have a `.linkedin_api` folder. Inside that `.linkedin_api` folder, you will find a `cookies` folder which contains all the cookies. Those are the cookies you want to delete; in your case, only one cookie file should exist.

For me, I believe my error was caused when I changed the password of my LinkedIn account. Once I changed the password, I ran my program (similar to your code) and got the same output as yours.

I am looking into this issue, and I plan on fixing it once I flesh out the details a bit more. In the meantime, any extra details can help me fix the bug. If my solution does not work for you, please describe any other pertinent details, and I will try to help.

I hope this helps.
