### ISSUE TITLE
Authentication doesn't work 

### ISSUE THREAD

**Issue by coreand** [tomquirk/linkedin-api#41]
Hello
I'm trying to execute basic authentication code: 
```
from linkedin_api import Linkedin
api = Linkedin('myEmailHere', 'myPasswordHere')
```
I got an error:
```
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 248, in _get_conn
    return conn or self._new_conn()
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 816, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /uas/authenticate (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Andrew/PycharmProjects/Crawlers/app/li/linkedin_com.py", line 24, in <module>
    main()
  File "C:/Users/Andrew/PycharmProjects/Crawlers/app/li/linkedin_com.py", line 20, in main
    api = Linkedin('*******', '*******')
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\linkedin_api\linkedin.py", line 37, in __init__
    self.client.authenticate(username, password)
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\linkedin_api\client.py", line 98, in authenticate
    self._set_session_cookies(self._request_session_cookies())
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\linkedin_api\client.py", line 76, in _request_session_cookies
    headers=Client.AUTH_REQUEST_HEADERS,
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Andrew\Anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /uas/authenticate (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```
I only hid username and password in the error output

**Comment by coreand** [comment]
The issue was with SSL package in Anaconda installation of Python. Usage of regular Python installer solved this for me.
