### ISSUE TITLE
Getting raise LinkedinSessionExpired linkedin_api.cookie_repository.LinkedinSessionExpired error

### ISSUE THREAD

**Issue by Prii-y** [tomquirk/linkedin-api#456]
Can someone help me out with this error I'm facing while using LinkedIn API. It was working fine last time when I tried but now it seems to give this issue. I tried deleting the LinkedIn API package and reinstalling it but it doesn't help. Here is the issue I'm facing. here is a screenshot.
`Traceback (most recent call last):
  File "c:\Users\priiy\Downloads\voyager\testapi.py", line 28, in <module>
    api = Linkedin(email, password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priiy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\linkedin_api\linkedin.py", line 82, in __init__
    self.client.authenticate(username, password)
  File "C:\Users\priiy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\linkedin_api\client.py", line 94, in authenticate
    cookies = self._cookie_repository.get(username)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\priiy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\linkedin_api\cookie_repository.py", line 38, in get
    raise LinkedinSessionExpired
linkedin_api.cookie_repository.LinkedinSessionExpired`

**Comment by miniquinox** [comment]
I am having the same issue... it used to work for me and not anymore

**Comment by fbuenohernandez** [comment]
https://github.com/tomquirk/linkedin-api/issues/461
