### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jdf159357** [tomquirk/linkedin-api#63]
after install linkedin-api，when import linkedin_api，SyntaxError: invalid syntax
>>> import linkedin_api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/linkedin_api/__init__.py", line 4, in <module>
    from .linkedin import Linkedin
  File "/usr/lib/python3.4/site-packages/linkedin_api/linkedin.py", line 48
    url = f"{self.client.API_BASE_URL}{uri}"
                                           ^

**Comment by tomquirk** [comment]
need to be using Python >=3.6 for the "f-strings"
