### ISSUE TITLE
Authenticating error

### ISSUE THREAD

**Issue by dimigor** [tomquirk/linkedin-api#81]
Getting an error 
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/dmytro/.pyenv/versions/linkedin_api/lib/python3.8/site-packages/linkedin_api/linkedin.py", line 37, in __init__
    self.client.authenticate(username, password)
  File "/home/dmytro/.pyenv/versions/linkedin_api/lib/python3.8/site-packages/linkedin_api/client.py", line 124, in authenticate
    self._set_session_cookies(res.cookies)
  File "/home/dmytro/.pyenv/versions/linkedin_api/lib/python3.8/site-packages/linkedin_api/client.py", line 84, in _set_session_cookies
    self.session.headers["csrf-token"] = self.session.cookies["JSESSIONID"].strip(
  File "/home/dmytro/.pyenv/versions/linkedin_api/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/dmytro/.pyenv/versions/linkedin_api/lib/python3.8/site-packages/requests/cookies.py", line 398, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='JSESSIONID', domain=None, path=None"
`

Seems like LinkedIn after auth does not return JSESSIONID cookie 
Any idea why?

**Comment by kingbar1990** [comment]
It's new linkedin V2 API. It need to rewrite API at all

**Comment by dimigor** [comment]
today it works well, have no idea what changed

**Comment by tomquirk** [comment]
Interesting 🤔 .

@kingbar1990 what is your experience? Have you been unable to authenticate previously?
